/**
 * Default CSV presets for the four tracked distributors. These seed the `csv_presets` table;
 * the importer always reads the mapping from the DB so dealers can be re-mapped without a deploy.
 */

import type { CsvColumnMap, NewCsvPreset } from "@/lib/db/schema";

export const DEFAULT_PRESETS: NewCsvPreset[] = [
  {
    vendorName: "lipseys",
    label: "Lipsey's",
    delimiter: ",",
    encoding: "utf-8",
    columnMap: {
      sku: ["Item #", "ItemNumber", "Item Number", "SKU"],
      upc: ["UPC", "UPC Code"],
      manufacturer: ["Manufacturer", "Mfg", "Brand"],
      model: ["Model", "Model Number"],
      description: ["Description", "Item Description"],
      caliber: ["Caliber", "Gauge", "Caliber/Gauge"],
      category: ["Type", "Category", "ItemType"],
      dealerPrice: ["Dealer Price", "Price", "Your Price"],
      msrp: ["MSRP", "Retail", "Retail Price"],
      qty: ["Quantity", "Qty", "On Hand"],
      onSale: ["Sale", "On Sale"],
      salePrice: ["Sale Price", "Special Price"],
    } satisfies CsvColumnMap,
  },
  {
    vendorName: "zanders",
    label: "Zanders Sporting Goods",
    delimiter: ",",
    encoding: "utf-8",
    columnMap: {
      sku: ["ITEM", "Item No", "SKU"],
      upc: ["UPC", "UPCCODE", "UPC Code"],
      manufacturer: ["MFG", "Manufacturer", "Brand"],
      model: ["MODEL", "Model"],
      description: ["DESCRIPTION", "Description"],
      caliber: ["CALIBER", "Caliber"],
      category: ["CATEGORY", "Type"],
      dealerPrice: ["PRICE", "Dealer", "Cost"],
      msrp: ["MSRP", "MAP"],
      qty: ["QTY", "Quantity", "Available"],
    } satisfies CsvColumnMap,
  },
  {
    vendorName: "davidsons",
    label: "Davidson's",
    delimiter: ",",
    encoding: "utf-8",
    columnMap: {
      sku: ["Item #", "Item Number", "ItemNumber", "Item No", "SKU", "MFG #", "Mfg #"],
      upc: ["UPC #", "UPC Code", "UPC", "UPCCode"],
      manufacturer: ["Manufacturer", "Mfg", "Brand", "MFG"],
      model: ["Model", "Model Number", "Model Series", "MFG #"],
      description: ["Description", "Item Description", "Product Description", "Title"],
      caliber: ["Caliber", "Gauge", "Caliber/Gauge"],
      category: ["Category", "Type", "Product Type"],
      dealerPrice: [
        "Dealer Price",
        "Dealer Cost",
        "Your Price",
        "Cost",
        "Price",
        "Price 1",
        "Price1",
        "Wholesale",
        "Unit Cost",
        "MSP",
      ],
      msrp: ["Retail", "MSRP", "Retail Price", "Price 2", "Price2"],
      mapPrice: ["MAP", "MAP Price", "Minimum Advertised Price", "Price 3", "Price3"],
      qty: ["Quantity Available", "Qty", "Quantity", "QOH", "On Hand"],
    } satisfies CsvColumnMap,
  },
  {
    vendorName: "chattanooga",
    label: "Chattanooga Shooting Supplies",
    delimiter: ",",
    encoding: "utf-8",
    columnMap: {
      sku: ["CSSI Item Number", "CSSI Item #", "Item Number", "Item #", "SKU", "Item"],
      upc: ["UPC", "UPC Code", "UPC #"],
      manufacturer: ["Manufacturer", "Mfg", "Mfg Name", "Brand"],
      model: ["Web Item Name", "Model Number", "Model", "Model #", "Manufacturer Item Number"],
      description: ["Product Description", "Item Description", "Description", "Desc"],
      caliber: ["Caliber", "Gauge"],
      category: ["Category", "Product Type", "Type"],
      dealerPrice: [
        "Price",
        "Dealer Price",
        "Dealer",
        "Dealer Cost",
        "Your Cost",
        "Your Price",
        "Cost",
        "Unit Price",
        "Wholesale",
      ],
      msrp: ["MSRP", "Retail", "Retail Price"],
      mapPrice: ["Retail MAP", "MAP", "MAP Price", "Minimum Advertised Price"],
      qty: ["Qty On Hand", "Quantity On Hand", "Qty", "Available", "QOH", "On Hand", "Quantity"],
    } satisfies CsvColumnMap,
  },
  {
    vendorName: "orion",
    label: "Orion Wholesale",
    delimiter: ",",
    encoding: "utf-8",
    columnMap: {
      sku: ["SKU", "Manufacturer SKU", "Item Number", "Item #"],
      upc: ["UPC", "UPC Code"],
      manufacturer: ["Brand", "Manufacturer", "Mfg"],
      model: ["Model", "Product Title", "Description"],
      description: ["Description", "Product Title", "Title"],
      caliber: ["Caliber", "Gauge"],
      category: ["Category", "Department"],
      dealerPrice: ["Price", "Dealer Price", "Your Price", "Cost"],
      msrp: ["MSRP", "Retail", "List Price"],
      qty: ["Qty", "Quantity", "Inventory"],
    } satisfies CsvColumnMap,
  },
  {
    vendorName: "2ndamendmentwholesale",
    label: "2nd Amendment Wholesale",
    delimiter: ",",
    encoding: "utf-8",
    columnMap: {
      sku: ["SKU", "sku", "Item Number", "Item #", "Item No", "Product SKU"],
      upc: ["UPC", "upc", "GTIN", "Barcode", "UPC Code"],
      manufacturer: ["Manufacturer", "Brand", "Mfg", "Vendor", "Attribute Manufacturer"],
      model: ["Model", "Model Number", "Model #", "MFG Model"],
      description: ["Name", "Product Name", "Description", "Short Description", "Title"],
      caliber: ["Caliber", "Caliber/Gauge", "Gauge", "Attribute Caliber"],
      category: ["Category", "Product Type", "Type", "Attribute Set", "Categories"],
      dealerPrice: [
        "Price",
        "Dealer Price",
        "Dealer Cost",
        "Cost",
        "Wholesale Price",
        "Your Price",
        "Special Price",
      ],
      msrp: ["MSRP", "Retail", "Retail Price"],
      mapPrice: ["MAP", "MAP Price", "Minimum Advertised Price"],
      qty: ["Qty", "Quantity", "Stock", "Qty On Hand", "Quantity On Hand", "In Stock", "Available"],
      onSale: ["On Sale", "Sale", "Special"],
      salePrice: ["Sale Price", "Special Price"],
    } satisfies CsvColumnMap,
  },
];
